Repository ADA-RLD/PostKit, pull requests merged in 2023-10, with the labels that each got.

#6 [Data/#1] Basic CoreData Setting
  PostKit/CoreData.xcdatamodeld/StoreCoreData.xcdatamodel/contents
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist~HEAD
  PostKit/PostKit.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist~develop
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/Model/DailyModel.swift
  PostKit/PostKit/Model/MenuModel.swift
  PostKit/PostKit/Model/StoreModel.swift
  PostKit/PostKit/PostKitApp.swift
  PostKit/PostKit/StoreCoreData.xcdatamodeld/.xccurrentversion
  PostKit/PostKit/StoreCoreData.xcdatamodeld/PostKit.xcdatamodel/contents
  PostKit/PostKit/ViewModel/DailyDataManager.swift
  PostKit/PostKit/ViewModel/MenuDataManager.swift
  PostKit/PostKit/ViewModel/StoreDataManager.swift
Labels: data

#9 [Data/#1] Add CoreData PRUD Protocol File
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/Model/DailyModel.swift
  PostKit/PostKit/Model/MenuModel.swift
  PostKit/PostKit/Protocol/DailyProtocol.swift
  PostKit/PostKit/Protocol/MenuProtocol.swift
  PostKit/PostKit/Protocol/StoreProtocol.swift
Labels: data

#10 [Feat/#8]Menu view 구현
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  PostKit/PostKit/Assets.xcassets/Gray1.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Gray2.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Gray3.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Gray4.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Gray5.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Gray6.colorset/Contents.json
  PostKit/PostKit/Model/KeywordsModel.swift
  PostKit/PostKit/Model/NavigationModel.swift
  PostKit/PostKit/Persistence.swift
  PostKit/PostKit/View/Component/CustomBtn.swift
  PostKit/PostKit/View/Component/CustomTextfield.swift
  PostKit/PostKit/View/Component/Keywords.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/MenuView.swift
  PostKit/PostKit/View/ResultView.swift
  PostKit/PostKit/View/extension/WrappingHStack.swift
  PostKit/PostKit/ViewModel/KeyboardObserver.swift
Labels: Feat

#13 [Feat/#3] Chat Gpt API 연결
  .gitignore
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Model/ChatGptModel.swift
  PostKit/PostKit/View/MenuView.swift
  PostKit/PostKit/ViewModel/ChatGptService.swift
Labels: Feat

#12 [Feat/#7] add Onboarding View
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/primary.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/secondary.colorset/Contents.json
  PostKit/PostKit/Model/ToneModel.swift
  PostKit/PostKit/Persistence.swift
  PostKit/PostKit/View/Component/CustomBtn.swift
  PostKit/PostKit/View/Component/CustomHeader.swift
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/OnboardingPage/OnboardingFinal.swift
  PostKit/PostKit/View/OnboardingPage/OnboardingIntro.swift
  PostKit/PostKit/View/OnboardingPage/OnboardingRouter.swift
  PostKit/PostKit/View/OnboardingPage/OnboardingStore.swift
  PostKit/PostKit/View/OnboardingPage/OnboardingTone.swift
  PostKit/PostKit/View/OnboardingPage/OnboardingView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
  PostKit/PostKit/View/extension/DesginSystem.swift
Labels: Feat

#18 [Fix/#17] Fix error in MenuView
  PostKit/PostKit/View/MenuView.swift
Labels: Fix

#30 [Feat] - 결과 화면에 ChatGpt API 연결
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/MenuView.swift
  PostKit/PostKit/View/ResultView.swift
  PostKit/PostKit/ViewModel/ChatGptViewModel.swift
Labels: Feat

#32 [Feat] - 일상 화면에 ChatGpt API 연결
  PostKit/PostKit/View/DailyView.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/MenuView.swift
  PostKit/PostKit/View/ResultView.swift
Labels: Feat

#35 [Fix] Git conflict error 해결
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
Labels: Fix

#38 [Fix/#34] Fix error
  PostKit/PostKit.xcodeproj/project.pbxproj
Labels: Fix

#40 [Fix] Fix error
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
Labels: Fix

#42 [Feat/#41] Apply AppStorage in prompt
  PostKit/PostKit/View/DailyView.swift
  PostKit/PostKit/View/MenuView.swift
  PostKit/PostKit/View/ResultView.swift
Labels: Feat

#46 [Feat/#45] LoadingView 연결
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/DailyView.swift
  PostKit/PostKit/View/LoadingView.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/MenuView.swift
  PostKit/PostKit/View/ResultView.swift
Labels: Feat

#53 [Chore/#52] Add scroll in result view
  PostKit/PostKit/View/ResultView.swift
Labels: Chore

#55 [Fix/#54] 패딩값 수정 데이터 점검 화면 연결 점검
  PostKit/PostKit/Model/ToneModel.swift
  PostKit/PostKit/View/LoadingView.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
  PostKit/PostKit/View/Setting/SettingView.swift
Labels: Chore

#57 [Chore] Hide indicator in ScrollView
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/ResultView.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
Labels: Chore

#62 [Data/#49] Now onBoardingView connected CoreData
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/Model/StoreModel.swift
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/Protocol/StoreProtocol.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
  PostKit/PostKit/ViewModel/DailyDataManager.swift
  PostKit/PostKit/ViewModel/MenuDataManager.swift
  PostKit/PostKit/ViewModel/StoreDataManager.swift
Labels: data

#65 [Data/#64] Now SettingView connected CoreData
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/PostKitApp.swift
  PostKit/PostKit/Protocol/SettingProtocol.swift
  PostKit/PostKit/Protocol/StoreProtocol.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
  PostKit/PostKit/View/Setting/SettingView.swift
Labels: data

#69 Rash refactor/#68
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/ContentArea.swift
  PostKit/PostKit/View/Component/CtaBtn.swift
  PostKit/PostKit/View/Component/CustomHeader.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
Labels: Refactor

#73 Rash fix/#72
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Extension/DesignSystem.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
Labels: Fix

#89 [Data/#77] DailyView sandMessage func connected CoreData
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/ViewModel/ChatGptViewModel.swift
Labels: data

#91 [Refactor] 온보딩 구조 변경
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
Labels: Refactor

#92 [Data/#77] MenuView connected with CoreData
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/PostKitApp.swift
  PostKit/PostKit/Protocol/CaptionResultProtocol.swift
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
  PostKit/PostKit/View/Setting/SettingView.swift
  PostKit/PostKit/ViewModel/CoreDataManager.swift
Labels: data

#93 [Fix/#83] Improving GPT results performance
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/MainView.swift
Labels: Feat

#100 [Feat] - 해시태그 생성 뷰 구현
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/CustomHashtag.swift
  PostKit/PostKit/View/Component/CustomTextfield.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
Labels: View

#103 [Data/#99] Onboarding View CoreData 연동
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/Protocol/SettingProtocol.swift
  PostKit/PostKit/Protocol/StoreProtocol.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
  PostKit/PostKit/View/Setting/SettingView.swift
Labels: data

#104 [Feat] - 해시태그 히스토리 뷰 구현
  PostKit/PostKit/Model/NavigationModel.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainView.swift
Labels: View

#106 [Data] - Onboarding, MainView CoreData func 수정
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
  PostKit/PostKit/View/Setting/SettingView.swift
Labels: data

#107 [Data] - Daily, Menu SendMessage에서 CoreData의 다중 Tone을 사용
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Protocol/CaptionResultProtocol.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
Labels: data

#110 [Data] - Caption Model, Protocol 추가
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Model/CaptionModel.swift
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/MainView.swift
Labels: data

#112 [Data/#108] captionResultView CoreData 연동
  PostKit/PostKit/Model/CaptionModel.swift
  PostKit/PostKit/View/MainView.swift
Labels: data

#114 [Data/#113] Hashtag CoreData 작업
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/Model/HashtagModel.swift
  PostKit/PostKit/Protocol/CaptionResultProtocol.swift
  PostKit/PostKit/Protocol/HashtagProtocol.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainView.swift
Labels: data

#115 [Data/#113] 메인뷰에서 Hashtag결과 출력
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/MainView.swift
Labels: data

#117 [Feat] Error 처리
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/ViewModel/ChatGptService.swift
  PostKit/PostKit/ViewModel/ResponseError.swift
Labels: Feat

#119 [Feat] 드래그제스처를 사용해서 뒤로가기 기능 추가
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Extension/Ex+UINaivgationController.swift
Labels: Feat

#123 [Fix/#122] 결과뷰 ScroolView refreshable 추가, 결과를 내림차순으로 정렬 추가
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/MainView.swift
Labels: bug, data, Fix

#126 [Feat] - 해시태그 생성 기능
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/ViewModel/HashtagService.swift
  PostKit/PostKit/ViewModel/HashtagViewModel.swift
Labels: Feat
