Repository ADA-RLD/PostKit, pull requests merged in 2023-11, with the labels that each got.

#127 [Fix/#122] 결과뷰 한글로 변경, 날짜 형식 변경
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainView.swift
Labels: data, Fix

#133 [Fix/#130] 이미 활성화된 버튼을 한번 더 클릭시 버튼 해제기능 추가
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Model/ToneModel.swift
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
Labels: Fix

#136 [Data/#131] 히스토리 LIke 기능 추가
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/Model/CaptionModel.swift
  PostKit/PostKit/Protocol/CaptionResultProtocol.swift
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/MainView.swift
Labels: data, Feat

#139 [Data/#137] 히스토리 수정 저장을 위해 변수 추가, 수정뷰가 나오면 Protocol 작성 예정
  PostKit/PostKit/Protocol/CaptionResultProtocol.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
Labels: data, Feat

#141 [Design] - Popover 구현
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Hashtag/HashtagPopover.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
Labels: Design

#145 [feat] - 믹스패널 연걸
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PostKit/PostKit/AppDelegate.swift
  PostKit/PostKit/PostKitApp.swift
Labels: Feat

#143 [Feat] - 크레딧 기능 추가 5회 부터 생성 가능
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/ViewModel/CoinManager.swift
Labels: Feat, Design

#146 [Data] 해쉬태그 Coredata 좋아요 추가, MainView 저장, fecth함수 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  PostKit/PostKit/Model/HashtagModel.swift
  PostKit/PostKit/Protocol/HashtagProtocol.swift
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainView.swift
Labels: data, Feat, Fix

#151 [Refactor] - Chat Gpt Service 리팩토링
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcodeproj/xcshareddata/xcschemes/PostKit.xcscheme
  PostKit/PostKit/Model/ChatGptModel.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/ViewModel/ChatGptService.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/HashtagService.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Refactor

#153 [Fix] - Change state variation to private variation
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Fix

#148 [Design] - HashtagView UI 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Extension/HashtagPopoverExtension.swift
  PostKit/PostKit/View/Hashtag/HashtagPopover.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
Labels: Design

#155 [Design/#154] - DailyView, MenuView 2번째 로우파이 적용
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/KeywordAppend.swift
  PostKit/PostKit/View/Component/SelectTextLength.swift
  PostKit/PostKit/ViewModel/CoinManager.swift
Labels: Design

#157 [Data] MainView 결과뷰에서 삭제하고 싶은 Caption을 누르면 삭제
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/MainView.swift
Labels: data, Feat

#159 [Data] 히스토리 코어데이터 삭제
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/MainView.swift
Labels: data, Feat

#160 [Chore] - Chatgpt API 연결 구조 변경
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/ViewModel/ChatGptService.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Feat, Fix, Chore

#161 [Feat] - 결과 수정화면 구현
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Component/HistoryButton.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
Labels: Feat, View

#164 [Fix] 오타 긴급 패치
  PostKit/PostKit/View/Component/HistoryButton.swift
Labels: Fix

#166 [Data] Caption 수정시 수정된 Caption이 저장되도록 함수 작성
  PostKit/PostKit/Protocol/CaptionResultProtocol.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
Labels: data, Feat

#168 [Feat] - 글 길이 선택 기능 구현
  PostKit/PostKit/Model/KeywordsModel.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/ViewModel/ChatGptViewModel.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Feat, Chore

#170 [Fix] 어플 최초 부팅 속도 상승
  PostKit/PostKit/Protocol/CaptionResultProtocol.swift
  PostKit/PostKit/Protocol/HashtagProtocol.swift
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/Protocol/MenuProtocol.swift
  PostKit/PostKit/Protocol/SettingProtocol.swift
  PostKit/PostKit/Protocol/StoreProtocol.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
Labels: Fix

#172 [Desing/#149] 로우파이적용
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Model/KeywordsModel.swift
  PostKit/PostKit/Model/ToneModel.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/CustomHeader.swift
  PostKit/PostKit/View/Component/KeywordAppend.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
Labels: Feat, Design

#174 [Feat] - 히스토리 수정화면 구현
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/MainView.swift
Labels: Feat, View

#177 [Feat] - Chat Gpt API 오류 처리
  PostKit/PostKit/Model/NavigationModel.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Error/ErrorView.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Feat

#179 [Data] 클라우드 연동 시도, 히스토리뷰 삭제 기능 추가, 해시태그 저장시 자동 fetch, 코인 삭제 버그 수정
  PostKit/Pods/Alamofire/Source/AFError.swift
  PostKit/Pods/Alamofire/Source/ServerTrustEvaluation.swift
  PostKit/Pods/Alamofire/Source/SessionDelegate.swift
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/PostKit.entitlements
  PostKit/PostKit/PostKitDebug.entitlements
  PostKit/PostKit/Protocol/HashtagProtocol.swift
  PostKit/PostKit/Protocol/iCloudProtocol.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
  PostKit/PostKit/ViewModel/CloudKitUserModel.swift
Labels: data, Feat

#180 [Desing/#175] 온보딩 하이파이 적용 및 asset추가
  PostKit/PostKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PostKit/PostKit/Assets.xcassets/Black.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray1.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray2.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray3.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray4.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray5.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray6.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Main.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Sub.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/logo.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/logo.imageset/logo 1.png
  PostKit/PostKit/Assets.xcassets/Colors/logo.imageset/logo.png
  PostKit/PostKit/Assets.xcassets/Colors/logo.imageset/logo3.png
  PostKit/PostKit/Assets.xcassets/Images/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/OnboardingFinalImage.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/OnboardingFinalImage.imageset/OnboardingFinalImage.svg
  PostKit/PostKit/Assets.xcassets/Images/OnboardingStartImage.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/OnboardingStartImage.imageset/OnboardingStart.svg
  PostKit/PostKit/Assets.xcassets/Images/coin.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/coin.imageset/coin.svg
  PostKit/PostKit/Assets.xcassets/Images/copy.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/copy.imageset/copy.svg
  PostKit/PostKit/Assets.xcassets/Images/exclamation.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/exclamation.imageset/exclamation.svg
  PostKit/PostKit/Assets.xcassets/Images/failedError.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/failedError.imageset/failed.svg
  PostKit/PostKit/Assets.xcassets/Images/gearShape.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/gearShape.imageset/gearShape.svg
  PostKit/PostKit/Assets.xcassets/Images/info.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/info.imageset/info.svg
  PostKit/PostKit/Assets.xcassets/Images/mainfeed.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/mainfeed.imageset/mainfeed.svg
  PostKit/PostKit/Assets.xcassets/Images/mainhashtag.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/mainhashtag.imageset/mainhashtag.svg
  PostKit/PostKit/Assets.xcassets/Images/networkError.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/networkError.imageset/network.svg
  PostKit/PostKit/Assets.xcassets/Images/pen.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/pen.imageset/pen.svg
  PostKit/PostKit/Assets.xcassets/White.colorset/Contents.json
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
Labels: Design

#182 [Data/#171] 히스토리뷰에서 수정, 삭제 구현
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Protocol/MainViewProtocol.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/MainView.swift
Labels: data, Feat

#183 [Design/#175] Asset 적용
  PostKit/PostKit/Assets.xcassets/Images/copy.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/copy.imageset/copy.svg
  PostKit/PostKit/Assets.xcassets/Images/error_failed.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/error_failed.imageset/failed.svg
  PostKit/PostKit/Assets.xcassets/Images/error_network.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/error_network.imageset/network.svg
  PostKit/PostKit/Assets.xcassets/Images/exclamation.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/exclamation.imageset/exclamation.svg
  PostKit/PostKit/Assets.xcassets/Images/gearShape.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/gearShape.imageset/gearShape.svg
  PostKit/PostKit/Assets.xcassets/Images/info.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/info.imageset/info.svg
  PostKit/PostKit/Assets.xcassets/Images/main_feed.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/main_feed.imageset/mainfeed.svg
  PostKit/PostKit/Assets.xcassets/Images/main_hashtag.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/main_hashtag.imageset/mainhashtag.svg
  PostKit/PostKit/Assets.xcassets/Images/onboarding_final_image.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/onboarding_final_image.imageset/OnboardingFinalImage.svg
  PostKit/PostKit/Assets.xcassets/Images/onboarding_start_image.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/onboarding_start_image.imageset/OnboardingStart.svg
  PostKit/PostKit/Assets.xcassets/Images/pen.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/pen.imageset/pen.svg
  PostKit/PostKit/Assets.xcassets/logo.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/logo.imageset/logo 1.png
  PostKit/PostKit/Assets.xcassets/logo.imageset/logo.png
  PostKit/PostKit/Assets.xcassets/logo.imageset/logo3.png
Labels: Design

#186 [Setting/#184] 디자인 시스템 적용
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
  PostKit/PostKit/View/Component/HistoryButton.swift
  PostKit/PostKit/View/Extension/DesignSystem.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/LoadingView.swift
  PostKit/PostKit/View/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
Labels: Setting, Design

#188 [Refactor] - 텝뷰 파일 분리
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/PostKitDebug.entitlements
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
Labels: Refactor

#190 [Design] - 토스트 메시지 UI 그리기
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
Labels: Design

#193 [Feat] Error View 구현
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Error/ErrorView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Feat, Design

#191 [Design/#189] - 온보딩 톤 수정, 셋팅뷰 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/ViewModel/CoinManager.swift
  PostKit/PostKit/ViewModel/ResponseError.swift
Labels: Design

#195 [Feat] - Gpt prompt 다듬기 & ChatGpt ViewModel 리팩토링
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Error/ErrorView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/ViewModel/CaptionResultViewModel.swift
  PostKit/PostKit/ViewModel/ChatGptViewModel.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/ErrorViewModel.swift
  PostKit/PostKit/ViewModel/Extension/StringExtension.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Feat, Fix, Refactor

#197 [QA] SelectToneView detail 수정
  PostKit/PostKit/Assets.xcassets/Colors/tertiary.colorset/Contents.json
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
Labels: Design, QA

#199 [Fix/#198] 버튼 한번 더 누를시 취소, 이름 빈칸시 버튼 비활성화
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
Labels: Fix

#202 [QA] Onboarding View QA 진행
  PostKit/PostKit/Model/AppStorageManager.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
  PostKit/PostKit/View/Setting/SettingStoreView.swift
  PostKit/PostKit/View/Setting/SettingView.swift
Labels: QA

#205 [Feat/#198] 믹스패널 기능 추가
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
  PostKit/PostKit/View/Error/ErrorView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/LoadingView.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
Labels: Feat

#204 [Design/#185] LoadingView HIFI 적용, 예외처리 버그 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/Images/loading_image.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/loading_image.imageset/loading_image.svg
  PostKit/PostKit/PostKitDebug.entitlements
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Error/ErrorView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Loading/LoadingCancelView.swift
  PostKit/PostKit/View/Loading/LoadingView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/ViewModel/CoinManager.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/LoadingViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: bug, Feat, Design

#207 [Design] - 히스토리 메인뷰 HIFI 적용
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/Icon/exclamation.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Icon/pen.imageset/Contents.json
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Component/CustomAlertMessage.swift
  PostKit/PostKit/View/Component/CustomHashtag.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Loading/LoadingView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
Labels: Design

#208 [Design/#203] MainCaptionView / TabView 디자인 적용
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/AccentColor.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/coin.imageset/coin.svg
  PostKit/PostKit/Assets.xcassets/Images/dailyImage.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/dailyImage.imageset/dailyImage.svg
  PostKit/PostKit/Assets.xcassets/Images/hashtagImage.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/hashtagImage.imageset/hashtagImage.svg
  PostKit/PostKit/Assets.xcassets/Images/menuImage.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/menuImage.imageset/menuImage.svg
  PostKit/PostKit/View/Loading/LoadingView.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
Labels: Design

#213 [Feat] - 코인 로직 구현
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/ViewModel/CaptionResultViewModel.swift
  PostKit/PostKit/ViewModel/CoinManager.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/ErrorViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Feat

#211 [Design] - 수정 모달 뷰 HIFI 적용
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
Labels: Design

#210 [Fix/#201] OnBoardingView에서 뒤로 돌아갈때 어플이 멈추는 버그 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
Labels: bug, Fix

#217 [Fix/#201] Fix onboardingview error
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingView.swift
Labels: Fix

#216 [Design] - 생성뷰 하이파이 적용
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/AppDelegate.swift
  PostKit/PostKit/Assets.xcassets/Colors/Gray1.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray2.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray3.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray4.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray5.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Gray6.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Main.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/Sub.colorset/Contents.json
  PostKit/PostKit/Assets.xcassets/Colors/tertiary.colorset/Contents.json
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/KeywordAppend.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
  PostKit/PostKit/View/Component/SelectTextLength.swift
  PostKit/PostKit/View/Extension/Ex+ATTrackingManager.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/ViewModel/CoinManager.swift
Labels: Design

#218 [Fix] Fix variation name
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/ViewModel/CoinManager.swift
Labels: Fix

#221 [Feat/#219] 믹스패널 프로퍼티 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/AppDelegate.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
  PostKit/PostKit/View/Error/ErrorView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Loading/LoadingView.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
Labels: Feat

#224 [QA] 일상 글 생성 뷰 QA 진행
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Component/CustomHashtag.swift
  PostKit/PostKit/View/Component/KeywordAppend.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
  PostKit/PostKit/View/Component/SelectTextLength.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
Labels: QA

#225 [Design] 히스토리 글 없을 때 뷰
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/Images/history_empty.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/history_empty.imageset/_레이어_1.svg
  PostKit/PostKit/Model/Constants.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Component/HistoryEmpty.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
Labels: Feat, Design

#227 [Feat/#222] Launch Screen 추가
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/launchLogo.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/launchLogo.imageset/launchLogo 1.svg
  PostKit/PostKit/Assets.xcassets/launchLogo.imageset/launchLogo 2.svg
  PostKit/PostKit/Assets.xcassets/launchLogo.imageset/launchLogo 3.svg
  PostKit/PostKit/Info.plist
Labels: Feat

#228 Joyce design/#178
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
Labels: Design

#232 [Fix/#214] 엄청난 여정이였다
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Component/CustomAlertMessage.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
Labels: Fix

#230 [Fix/#222] App Icon 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/AppIcon.appiconset/AppIcon.jpg
  PostKit/PostKit/Assets.xcassets/AppIcon.appiconset/Contents.json
  PostKit/PostKit/Assets.xcassets/AppIcon.appiconset/Logo.png
Labels: Design

#231 [Chroe] 개인정보 처리방침 추가
  README.md
Labels: Chore

#233 [Design/#226] 해시태그 생성뷰 하이파이 적용
  PostKit/PostKit/Assets.xcassets/Icon/info.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Icon/info.imageset/info.svg
  PostKit/PostKit/Assets.xcassets/Images/error_failed.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/error_failed.imageset/error_failed.svg
  PostKit/PostKit/Assets.xcassets/Images/error_failed.imageset/failed.svg
  PostKit/PostKit/View/Hashtag/HashtagView.swift
Labels: Design

#234 [Fix/#185] 직접 추가한 변수가 로딩뷰에 나오지 않는 버그 수정
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
Labels: bug, Fix

#237 [Fix/#229] 생성뷰 오류 수정 및 전체적인 패딩값 조정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/Icon/info.imageset/Contents.json
  PostKit/PostKit/Model/Constants.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/KeywordAppend.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
  PostKit/PostKit/View/Component/SelectTextLength.swift
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
  PostKit/PostKit/ViewModel/ChatGptService.swift
Labels: Fix

#239 [Fix] 해쉬태그 로딩뷰, 해시태그 수정시 다중 저장 버그 수정
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
Labels: bug, Fix

#241 [Feat] - 글 생성시 코인 부족 Alert
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/Images/history_empty.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/history_empty.imageset/historyEmpty.svg
  PostKit/PostKit/Model/Constants.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/CustomAlertMessage.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
Labels: Feat

#242 [Design/#240] 디자인 수정 및 함수 뷰모델화
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Extension/Ex+UINaivgationController.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/ViewModel/CaptionResultViewModel.swift
  PostKit/PostKit/ViewModel/CopyManger.swift
Labels: Design

#244 [Fix/#235] Cloud 연동 삭제, 버전 +1, Gpt 키값 변경
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/ViewModel/CloudKitUserModel.swift
Labels: Fix

#247 [Fix/#246] 해시태그가 중복 저장되는 버그 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/ViewModel/HashtagViewModel.swift
Labels: bug, Fix

#253 [Fix/#252] 온보딩 말투 뷰에서 이탈하면 선택된 말투가 초기화되는 버그
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
Labels: bug, Fix

#258 [Fix] - QA 1차 반영_로딩 뷰 및 코인 로직
  PostKit/PostKit/Model/Constants.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Component/CTABtn.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Loading/LoadingView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/ViewModel/CoinManager.swift
Labels: Feat, Fix, Design

#255 [Fix/#254] 1차 QA - Icon, TabView, Writing, Padding, LightMode 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Assets.xcassets/Icons/exclamation.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Icons/heart.imageset/heart.svg
  PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
  PostKit/PostKit/View/Component/HistoryEmpty.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/ViewModel/ChatGptService.swift
Labels: Fix

#256 [Fix/#245] 1차 QA 반영 - 탭바 영역, 키워드 동일 내용 입력방지, 토스트 수정, 텍스트 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
Labels: Fix

#251 [Fix/#250] 해시태그 뷰에서 키워드를 작성하고 다른 곳을 눌러도 키워드가 저장됩니다.
  PostKit/PostKit/View/Hashtag/HashtagView.swift
Labels: Feat, Fix

#261 [Fix/#259] 6,7번뷰 QA
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
Labels: Fix, QA

#265 [Fix] 2차 QA 수정 - 1
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Component/HistoryEmpty.swift
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
  PostKit/PostKit/View/Setting/SettingToneView.swift
Labels: Fix
