Repository ADA-RLD/PostKit, pull requests merged in 2024-04, with the labels that each got.

#329 [Refactor/#328] 필요없는 파일 삭제 및 오류수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Model/CaptionModel.swift
  PostKit/PostKit/Model/NavigationModel.swift
  PostKit/PostKit/View/Caption/BrowShopView.swift
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/FashionView.swift
  PostKit/PostKit/View/Caption/GoodsView.swift
  PostKit/PostKit/View/Caption/HairView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/ViewModel/BrowShopViewModel.swift
  PostKit/PostKit/ViewModel/CaptionResultViewModel.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/Extension/Ex+View.swift
  PostKit/PostKit/ViewModel/FashionViewModel.swift
  PostKit/PostKit/ViewModel/FirebaseManager.swift
  PostKit/PostKit/ViewModel/GoodsViewModel.swift
  PostKit/PostKit/ViewModel/HairViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Feat, Fix, Refactor

#330 [Refactor/#321] QA 마무리
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Component/KeywordAppend.swift
  PostKit/PostKit/View/Extension/ImageWrappingHstack.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
Labels: Refactor

#333 [QA/#332] 뷰구조 변경으로 인한 추가 QA
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PostKit/PostKit/View/Caption/CaptionView.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
  PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
  PostKit/PostKit/View/Onboarding/OnboardingStore.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
Labels: Fix, QA

#335 [Fix/#334] 전체화면 광고가 뜨지 않던 오류 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PostKit/PostKit/View/Loading/LoadingView.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/ViewModel/GoogleAdmob.swift
Labels: bug, Fix

#337 Andy release/#336
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PostKit/PrivacyInfo.xcprivacy
Labels: Setting

#339 [QA/ 338] 추가 QA 및 배포 준비
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Component/KeywordAppend.swift
  PostKit/PostKit/ViewModel/CaptionViewModel.swift
  PostKit/PostKit/ViewModel/FirebaseManager.swift
Labels: Fix, QA

#341 [Fix/#340] 온보딩 예시 문장 수정
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PostKit/PostKit/View/Component/SelectTone.swift
  PostKit/PostKit/View/Onboarding/OnboardingTone.swift
  PostKit/PostKit/ViewModel/FirebaseManager.swift
Labels: Fix

#342 [TestFlight] TestFlight 업로드, 스토어 업로드 준비
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Setting

#343 [Release/336] Dev에서 Release API 변경
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/AppDelegate.swift
  PostKit/PostKit/ViewModel/FirebaseManager.swift
Labels: Setting
