Repository ADA-RLD/PostKit, pull requests merged in 2024-02, with the labels that each got.

#293 [Design] 신기능 추가로 인한 디자인 변경 추가
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/GoodsView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
  PostKit/PostKit/View/MainViews/MainView.swift
  PostKit/PostKit/ViewModel/GoodsViewModel.swift
Labels: Design

#294 [Feat] 이미지 퍼미션, 이미지 추가 뷰 완료
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/KeywordAppend.swift
  PostKit/PostKit/View/Extension/ImageWrappingHstack.swift
Labels: Feat

#299 [Feat/#298] Gpt API 호출구조 변경
  PostKit/GoogleService-Info.plist
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/Model/APIModel.swift
  PostKit/PostKit/Model/ChatGptModel.swift
  PostKit/PostKit/Model/ChatGptVisionModel.swift
  PostKit/PostKit/Model/File.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Caption/GoodsView.swift
  PostKit/PostKit/View/Caption/MenuView.swift
  PostKit/PostKit/View/Component/KeywordModal.swift
  PostKit/PostKit/ViewModel/APIManager.swift
  PostKit/PostKit/ViewModel/CaptionResultViewModel.swift
  PostKit/PostKit/ViewModel/ChatGptService.swift
  PostKit/PostKit/ViewModel/ChatGptViewModel.swift
  PostKit/PostKit/ViewModel/DailyViewModel.swift
  PostKit/PostKit/ViewModel/ErrorViewModel.swift
  PostKit/PostKit/ViewModel/GoodsViewModel.swift
  PostKit/PostKit/ViewModel/GptVisionService.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Feat

#302 [Fix/#301] 긴급 오류 수정 및 gitignore 변경
  .gitignore
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Caption/CaptionResultView.swift
  PostKit/PostKit/View/Caption/DailyView.swift
  PostKit/PostKit/View/Hashtag/HashtagResultView.swift
  PostKit/PostKit/View/Hashtag/HashtagView.swift
  PostKit/PostKit/View/Loading/LoadingView.swift
  PostKit/PostKit/ViewModel/GoodsViewModel.swift
  PostKit/PostKit/ViewModel/MenuViewModel.swift
Labels: Fix

#303 [View/#300] 해시태그 기능 삭제
  PostKit/PostKit.xcodeproj/project.pbxproj
  PostKit/PostKit/View/Component/HistoryEmpty.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
  PostKit/PostKit/View/MainViews/MainHistoryView.swift
Labels: View

#305 [View/#304] 메인뷰 새로운 디자인 적용
  PostKit/PostKit/Assets.xcassets/Icons/Brow.imageset/Brow.svg
  PostKit/PostKit/Assets.xcassets/Icons/Brow.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Icons/Cafe.imageset/Cafe.svg
  PostKit/PostKit/Assets.xcassets/Icons/Cafe.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Icons/Fashion.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Icons/Fashion.imageset/Fashion.svg
  PostKit/PostKit/Assets.xcassets/Icons/Hair.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Icons/Hair.imageset/Hair.svg
  PostKit/PostKit/Assets.xcassets/Images/launchLogo.imageset/Contents.json
  PostKit/PostKit/Assets.xcassets/Images/launchLogo.imageset/launchLogo 1.svg
  PostKit/PostKit/Assets.xcassets/Images/launchLogo.imageset/launchLogo 2.svg
  PostKit/PostKit/Assets.xcassets/Images/launchLogo.imageset/launchLogo 3.svg
  PostKit/PostKit/Assets.xcassets/Lottie/Contents.json
  PostKit/PostKit/Assets.xcassets/Lottie/LoadingLottie.dataset/Contents.json
  PostKit/PostKit/Assets.xcassets/Lottie/LoadingLottie.dataset/PK-Loading.json
  PostKit/PostKit/Assets.xcassets/logo.imageset/logo 1.png
  PostKit/PostKit/Assets.xcassets/logo.imageset/logo.png
  PostKit/PostKit/Assets.xcassets/logo.imageset/logo3.png
  PostKit/PostKit/Model/CaptionModel.swift
  PostKit/PostKit/Model/NavigationModel.swift
  PostKit/PostKit/View/MainViews/MainCaptionView.swift
Labels: View
